const aidaset = {
    RUNNING_TIME:{
        dis:"UTIL",
        type:"已运行时间",
        unit:"秒"
    },
    CPU_FREQUENCY:{
        dis:"CPU",
        type:"CPU频率",
        unit:"MHz"
    },
    CPU_USAGE:{
        dis:"CPU",
        type:"CPU使用率",
        unit:"%"
    },
    MEMORY_USAGE:{
        dis:"RAM",
        type:"内存已使用",
        unit:"MB"
    },
    MEMORY_UNUSED:{
        dis:"RAM",
        type:"内存可用",
        unit:"MB"
    },
    VMEMORY_USAGE:{
        dis:"RAM",
        type:"虚拟内存已使用",
        unit:"MB"
    },
    VMEMORY_UNUSED:{
        dis:"RAM",
        type:"虚拟内存可用",
        unit:"MB"
    },
    CPU_UNIT_USAGE:{
        dis:"CPU",
        type:"CPU核心%d使用率",
        unit:"%"
    },
    CPU_TEMPERATURE:{
        dis:"CPU",
        type:"CPU温度",
        unit:"℃"
    },
    CPU_WASTES:{
        dis:"CPU",
        type:"CPU功耗(package)",
        unit:"W"
    },
    DISKIO_USAGE:{
        dis:"DISK",
        type:"磁盘%d利用率",
        unit:"GB"
    },
    DISKI_SPEED:{
        dis:"DISK",
        type:"磁盘%d读取速度",
        unit:"KB/s"
    },
    DISK_TEMPERATURE:{
        dis:"DISK",
        type:"磁盘%d温度",
        unit:"℃"
    },
    DRIVER_USAGE:{
        dis:"DISK",
        type:"驱动器%s已使用",
        unit:"GB"
    },
    DRIVER_UNUSED:{
        dis:"DISK",
        type:"驱动器%s可用",
        unit:"GB"
    },
    DISKO_SPEED:{
        dis:"DISK",
        type:"磁盘%d写入速度",
        unit:"KB/s"
    },
    EXTERNAL_IP:{
        dis:"UTIL",
        type:"外部ip",
        unit:""
    },
    NIC_MAXSPEED:{
        dis:"NET",
        type:"NIC%d最大速率",
        unit:"Mbps"
    },
    NIC_USPEED:{
        dis:"NET",
        type:"NIC%d上传速度",
        unit:"KB/s"
    },
    NIC_DSPEED:{
        dis:"NET",
        type:"NIC%d下载速度",
        unit:"KB/s"
    },
    NIC_UPLOAD:{
        dis:"NET",
        type:"NIC%d上传总量",
        unit:"MB"
    },
    NIC_DOWNLOAD:{
        dis:"NET",
        type:"NIC%d下载总量",
        unit:"MB"
    },
    GRAM_USAGE:{
        dis:"GPU",
        type:"显存已使用",
        unit:"MB"
    },
    GRAM_UNUSED:{
        dis:"GPU",
        type:"显存可用",
        unit:"MB"
    },
    GPU_USAGE:{
        dis:"GPU",
        type:"显卡使用率",
        unit:"%"
    },
    GPU_TEMPERATURE:{
        dis:"GPU",
        type:"显卡温度",
        unit:"℃"
    },
    GPU_WASTES:{
        dis:"GPU",
        type:"显卡功耗比",
        unit:"%"
    },
    GT_WASTES:{
        dis:"GPU",
        type:"核显功耗",
        unit:"W"
    },
    GT_TEMPERATURE:{
        dis:"GPU",
        type:"核显温度",
        unit:"℃"
    },
    MB_TEMPERATURE:{
        dis:"UTIL",
        type:"主板温度",
        unit:"℃"
    },
    POWER_STAT:{
        dis:"UTIL",
        type:"电池状态",
        unit:""
    },
    POWER_LEVEL:{
        dis:"UTIL",
        type:"电量",
        unit:"%"
    },
    SYSTEM_PROCESSING:{
        dis:"UTIL",
        type:"进程数量",
        unit:""
    }
};
